#spring.application.name=demo
#
#spring.ai.openai.base-url=https://api.groq.com/openai/v1
#spring.ai.openai.chat.options.model=openai/gpt-oss-20b

spring.application.name=demo

spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=openai/gpt-oss-20b
spring.ai.openai.api-key=${GROQ_API_KEY}