spring.application.name=demo

spring.ai.openai.base-url=https://api.groq.com/openai/v1
#spring.ai.openai.chat.options.model=openai/gpt-oss-20b
#spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.chat.options.model=qwen/qwen3.8-27b

weather.api.key=
#spring.ai.openai.chat.extra-body.reasoning_effort=none
spring.ai.openai.chat.max-tokens=12000